# Generated by Django 5.0.6 on 2025-03-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("servers", models.IntegerField(default=0)),
                ("vms", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Server1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("hardware_name", models.CharField(max_length=255)),
                ("cpu_model", models.CharField(max_length=255)),
                ("memory", models.CharField(max_length=255)),
                ("storage", models.CharField(max_length=255)),
                ("network_info", models.CharField(max_length=255)),
                ("firmware_version", models.CharField(max_length=255)),
                ("power_cooling", models.CharField(max_length=255)),
                ("cpu_utilisation", models.CharField(max_length=255)),
                ("memory_usage", models.CharField(max_length=255)),
                ("nics", models.CharField(max_length=255)),
                ("load_average", models.CharField(max_length=255)),
                ("os_version", models.CharField(max_length=255)),
                ("hypervisor_details", models.CharField(max_length=255)),
                ("ip_address", models.CharField(max_length=255)),
                ("mac_address", models.CharField(max_length=255)),
                ("routing_tables", models.CharField(max_length=255)),
                ("dns_dhp", models.CharField(max_length=255)),
                ("switch_info", models.JSONField(max_length=255)),
                ("idrac_ip", models.CharField(max_length=255)),
                ("pxe_address", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
                (
                    "server_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.servertype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ipv4_address", models.CharField(max_length=255)),
                ("ipv6_address", models.CharField(max_length=255)),
                ("idrac_ilo_ip", models.CharField(max_length=255)),
                ("default_gateway", models.CharField(max_length=255)),
                ("Dns_server_ip", models.CharField(max_length=255)),
                ("storage", models.CharField(max_length=255)),
                ("total_cups", models.CharField(max_length=255)),
                ("total_Sockets", models.CharField(max_length=255)),
                ("cores_per_socket", models.CharField(max_length=255)),
                ("threads_per_core", models.CharField(max_length=255)),
                ("nics", models.CharField(max_length=255)),
                ("cpu_average", models.CharField(max_length=255)),
                ("memory", models.CharField(max_length=255)),
                ("ip_address", models.CharField(max_length=255)),
                ("hard_drives_name", models.CharField(max_length=255)),
                ("hard_model", models.CharField(max_length=255)),
                ("hard_drives_size", models.CharField(max_length=255)),
                ("os_version", models.CharField(max_length=255)),
                ("kernel_version", models.CharField(max_length=255)),
                ("uptime", models.CharField(max_length=255)),
                ("vendor", models.CharField(max_length=255)),
                ("server_model", models.CharField(max_length=255)),
                ("cpu_series", models.CharField(max_length=255)),
                ("bios_version", models.CharField(max_length=255)),
                ("bios_release", models.CharField(max_length=255)),
                ("serial_number", models.CharField(max_length=255)),
                ("att_patch_level", models.CharField(max_length=255)),
                ("running_vms", models.CharField(max_length=255)),
                ("switch_info", models.JSONField(max_length=255)),
                (
                    "server_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.servertype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vcpus", models.CharField(max_length=255)),
                ("memory", models.CharField(max_length=255)),
                ("disk_space", models.CharField(max_length=255)),
                ("network_interface", models.CharField(max_length=255)),
                ("guest_os", models.CharField(max_length=255)),
                ("vcpu_utilisation", models.CharField(max_length=255)),
                ("memory_usage", models.CharField(max_length=255)),
                ("disk_io", models.CharField(max_length=255)),
                ("load_average", models.CharField(max_length=255)),
                ("io_wait", models.CharField(max_length=255)),
                ("swap_usage", models.CharField(max_length=255)),
                ("app_type", models.CharField(max_length=255)),
                ("mots_id", models.CharField(max_length=255)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.server"
                    ),
                ),
            ],
        ),
    ]
